name: Test

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/test.yml
      - src/run.ts

permissions:
  contents: write

jobs:
  # win32 x64
  test_win32:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build and run
        run: |
          npm ci
          npm run build
          node dist/run.js

      - name: Create test archive
        run: |
          cd tests
          ../7zip/win32_x64_7z.exe a "data/test win32.7z" ".temp/inner folder" ".temp/test 1.txt" ".temp/test 2.txt"
          dir data

      - name: Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add tests
          git commit -m "chore: generate test archive for windows"
          git push

  # linux x64
  test_linux:
    runs-on: ubuntu-latest
    needs: test_win32
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build and run
        run: |
          npm ci
          npm run build
          node dist/run.js

      - name: Create test archive
        run: |
          chmod +x 7zip/linux_x64_7z
          cd tests
          ../7zip/linux_x64_7z a "data/test linux.7z" ".temp/inner folder" ".temp/test 1.txt" ".temp/test 2.txt"
          ls -al data

      - name: Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add tests
          git commit -m "chore: generate test archive for linux"
          git push

  # darwin arm64
  test_darwin:
    runs-on: macos-latest
    needs: test_linux
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build and run
        run: |
          npm ci
          npm run build
          node dist/run.js

      - name: Create test archive
        run: |
          chmod +x 7zip/darwin_7z
          cd tests
          ../7zip/darwin_7z a "data/test darwin.7z" ".temp/inner folder" ".temp/test 1.txt" ".temp/test 2.txt"
          ls -al data

      - name: Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add tests
          git commit -m "chore: generate test archive for darwin"
          git push
