name: Test

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/test.yml
      - src/run.ts

jobs:
  test_windows: # win32 x64
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: |
          npm ci
          npm run build
          node dist/run.js

  test_ubuntu: # linux x64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: |
          chmod +x 7zip/linux_x64_7z
          npm ci
          npm run build
          node dist/run.js

  test_macos: # darwin arm64
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: |
          chmod +x 7zip/darwin_7z
          npm ci
          npm run build
          node dist/run.js
