name: Test

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/test.yml
      - src/run.ts

jobs:
  # win32 x64
  test_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Run
        run: node dist/run.js

      - name: Zip
        run: |
          cd tests
          mkdir data
          ../7zip/win32_x64_7z.exe a "data/test win32.7z" ".temp/inner folder" ".temp/test 1.txt" ".temp/test 2.txt"
          dir data

  # # linux x64
  # test_ubuntu:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         lfs: true

  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: '20'

  #     - run: |
  #         npm ci
  #         npm run build

  #     - run: |
  #         chmod +x 7zip/linux_ia32_7z
  #         chmod +x 7zip/linux_x64_7z
  #         chmod +x 7zip/linux_arm_7z
  #         chmod +x 7zip/linux_arm64_7z
  #         node dist/run.js

  # # darwin arm64
  # test_macos:
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         lfs: true

  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: '20'

  #     - run: |
  #         npm ci
  #         npm run build

  #     - run: |
  #         chmod +x 7zip/darwin_7z
  #         node dist/run.js
