name: Test

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/test.yml

jobs:
  test_windows: # win32 x64
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: '20'

      # - run: |
      #     npm ci
      #     npm run build
      #     node dist/run.js

      - run: |
          cd 7zip
          ./win32_x64_7z.exe -version


  test_ubuntu: # linux x64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: '20'

      # - run: |
      #     npm ci
      #     npm run build
      #     node dist/run.js

      - run: |
          cd 7zip
          chmod +x ./linux_x64_7z
          ./linux_x64_7z -version

  test_macos: # darwin arm64
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: '20'

      # - run: |
      #     npm ci
      #     npm run build
      #     node dist/run.js

      - run: |
          cd 7zip
          chmod +x ./darwin_7z
          ./darwin_7z -version
